### ISSUE TITLE
Dolphin theme not applying properly

### ISSUE THREAD

**Issue by Myfeet-smell** [Humanoidear/Lightsout#3]
![medkmqkwldmqkwlmdqwlkdklqwmdklqwmd](https://user-images.githubusercontent.com/102279968/159852986-aac0dbbb-ed68-4ae0-a6b9-48eb69344e19.PNG)
It is not applying correctly on 5.0-16101

**Comment by Myfeet-smell** [comment]
Nevermind it was because I'm dumb lol

**Comment by Humanoidear** [comment]
Glad to know it worked out in the end! 😊
